# Analysis

Playing around a bit with the index

```{r}
library(tidyverse)
```

```{r}
df_cleaned <- read_csv("../../data/intermediate/03_Index.csv")
```



## Look

```{r}
df_analysis <- df_cleaned %>% pivot_wider(names_from = year, values_from = commodity_index)
```

```{r}
df_analysis %>%
  # histogram
  ggplot(aes(x = `2013`, label= ISO3)) +
    geom_histogram() 
```


## Quick Plot

= Chile as a case example

Why is CHL sooo high?
- high number for price of copper (2900)
- high weight in export (0.92)
=> 2900^0.92 = more than 1000

```{r}
C <- "CHL"
```


1: Raw Index: 
```{r}
df_index_raw %>%
  filter(country_iso3 == C) %>%
  ggplot(aes(x = year, y = index)) +
    geom_line() 
```

2: With deflating and trade volume adjustment
```{r}
df_index_real %>%
  filter(country_iso3 == C) %>%
  ggplot(aes(x = year, y = index)) +
    geom_line() 
```

3: with GDP weighting

```{r}
df_index_gdp_weighted %>%
  filter(country_iso3 == C) %>%
  ggplot(aes(x = year, y = index_gdp_weighted)) +
    geom_line()
```



```{r}
p <- df_cleaned %>%
  filter(
    ISO3 %in% c(
      # make the plot for 30 large economies
      "USA", "CHN", "JPN", "DEU", "IND", "GBR", "FRA", "ITA", "BRA", "CAN",
      "RUS", "KOR", "ESP", "AUS", "MEX", "IDN", "NLD", "SAU", "TUR",
      "ARG", "SWE", "POL", "BEL", "THA", "NGA", "AUT", "IRN", "NOR", "ISR", "CHL", "BRA"
    )
  ) %>%
  # filter(!ISO3 %in% c("ZMB", "QAT")) %>%
  # filter(ISO3 == "CHL") %>%
  ggplot(aes(x = year, y = commodity_index, color=ISO3)) +
    geom_line() 

plotly::ggplotly(p)
```

