# Combining the data and producing summary statistics

```{r}
library(tidyverse)
library(haven)
```


## Load the datasets

```{r}
df_wesp <- read_dta("../../data/processed/01_WESP.dta")
df_gmd <- read_dta("../../data/processed/02_GMD.dta")
df_wdi <- read_dta("../../data/processed/03_WDI.dta")
df_imf <- read_dta("../../data/processed/04_IMF_data.dta")
df_wid <- read_dta("../../data/processed/05_WID.dta")
df_conf <- read_dta("../../data/processed/06_Conf_Board.dta")
df_index <- read_dta("../../data/processed/07_Misc_Ind.dta")
```

```{r}
df_comm <- read_dta("../../data/processed/_03_Index.dta")
```

```{r}
df_imf <- df_imf %>%
  # convert all "" to NA
  mutate(across(everything(), ~ na_if(., "")))
```


## Combine the datasets

```{r}
df_gmd <- df_gmd %>% mutate(year = as.integer(year))
df_wdi <- df_wdi %>% mutate(year = as.integer(year))
df_imf <- df_imf %>% mutate(year = as.integer(year))
df_wid <- df_wid %>% mutate(year = as.integer(year))
df_conf <- df_conf %>% mutate(year = as.integer(year))
df_comm <- df_comm %>% mutate(year = as.integer(year))
```


```{r}
df_combined <- df_gmd %>%
  left_join(df_wesp, by = c("ISO3")) %>%
  full_join(df_wdi, by = c("ISO3", "year")) %>%
  full_join(df_imf, by = c("ISO3", "year")) %>%
  full_join(df_wid, by = c("ISO3", "year")) %>%
  full_join(df_conf, by = c("ISO3", "year")) %>%
  full_join(df_index, by = c("ISO3", "year")) %>%
  full_join(df_comm, by = c("ISO3", "year"))
```

```{r}
df_combined <- df_combined %>%
  filter(ISO3 %in% df_wesp$ISO3) 
```



## Save the combined dataset

```{r}
write_dta(df_combined, "../../data/processed/final_data.dta")
write_csv(df_combined, "../../data/processed/final_data.csv")
```
