# Economic Complexity Index and growth?

## Imports

```{r}
library(tidyverse)
library(haven)
```

```{r}
df <- read_dta("../../data/processed/final_data.dta")
```

## Idea Nr. 1

Idea: 

- countries with more stronger producitve capabilites -> grow faster
- more spohistication + diversification

Analysis

- ECI for a given year (2005, 2010)
- GDP growth in subsequent decade
- scatter plot

```{r}
start_year <- 2010
end_year <- 2020

df %>%
  select(country, year, eci, labor_productivity_person_growth) %>%
  filter(year %in% c(start_year, end_year)) %>%
  group_by(country) %>%
  reframe(
    eci = first(eci),
    labor_productivity_person_growth = as.numeric(labor_productivity_person_growth),
    gdp_growth = ( (last(labor_productivity_person_growth) / first(labor_productivity_person_growth))^(1/9) - 1) *100, #CAGR
  ) %>%
  filter(!is.na(eci)) %>%
  ggplot(aes(x = eci, y = gdp_growth)) +
  geom_point() +
  geom_smooth(method = "lm", se = T) +
  labs(
    title= paste0("ECI in ", start_year, " vs.  growth in ", start_year, "-", end_year),
    x = "Economic Complexity Index",
    y = "CAGR %"
    ) 
```

Countries that increases ECI the most in last 10 years
```{r}
df %>%
  select(country, year, eci) %>%
  filter(year %in% c(start_year, end_year)) %>%
  group_by(country) %>%
  reframe(
    eci_start = first(eci),
    eci_end = last(eci),
    eci_change = eci_end - eci_start
  ) %>%
  arrange(desc(eci_change)) 
```

